#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0_orig 0

# Initialize via expressions
runApplication setExprFields

# Decompose
runApplication decomposePar -latestTime

# Run
runParallel `getApplication`

# Reconstruct
runApplication reconstructPar -newTimes -fields 'p'





